server:
  port: 8200

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-acl
          uri: lb://service-acl
          predicates:
            - Path=/*/acl/**

        - id: service-sys
          uri: lb://service-sys
          predicates:
            - Path=/*/sys/**

        - id: service-word
          uri: lb://service-word
          predicates:
            - Path=/*/product/**


        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**

        - id: service-home
          uri: lb://service-home
          predicates:
            - Path=/*/home/**

